name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Получаем исходный код
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      # Шаг 3: Устанавливаем зависимости
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Шаг 4: Запускаем тесты
      - name: Run Tests
        run: |
          pytest tests/
